### ISSUE TITLE
Provide a browser-ready bundle

### ISSUE THREAD

**Issue by damianmr** [stayradiated/react-colorpicker#14]
Hello, I wanted to use this component in a Rails project and noticed that there's no browser ready package. That is, there's no single js file (plus some basic CSS) to just add to your project and start using the lib.

I wanted to use the JS that is in the example page, but the whole example is bundled as an app (instead of bundling the library and the actual app in separate files).

**Comment by stayradiated** [comment]
I think I've got a standalone browser library working. I haven't tested it with the example app though.

Check it out in the [./browser](https://github.com/stayradiated/react-colorpicker/tree/master/browser) folder. It exports as `window.ReactColorpicker`.

The standalone files do not include the React library, so you'll need to load that in separately.
