### ISSUE TITLE
React 0.13 compatibility

### ISSUE THREAD

**Issue by tmcw** [stayradiated/react-colorpicker#16]
It doesn't look like this module is compatible with React 0.13 - it tries to mutate the `props` argument and fails to build a component

**Comment by stayradiated** [comment]
I've just tried updating to React 0.13 and it seems to be working ok. The only warrning I'm getting is about the deprecation of the `classSet` addon.

Could you please post more information about the error you are getting.

**Comment by stayradiated** [comment]
Ah, I just realised that v0.3.10 never got published to NPM.

I've just published 0.3.11, which includes fixes for the `classSet` warning. Try that and see if it fixes the issue.

**Comment by tmcw** [comment]
Gotcha - that fixes the issue, thanks!
