### ISSUE TITLE
Cannot find module 'react-colorpicker'

### ISSUE THREAD

**Issue by importre** [stayradiated/react-colorpicker#17]
i got `Cannot find module 'react-colorpicker'` error message.

`package.json`
```json
{
  ...
  "browser": "react-colorpicker.js",
  ...
}
```

`.npmignore`
```
/example
/lib
/maps
/gulpfile.js
/browser >>>>>> this directory is ignored.
```

**Comment by stayradiated** [comment]
I've just published v0.3.12 which includes the browser folder in the package.

**Comment by patryk-g** [comment]
Hello,

I've got this working few days ago but I needed to rebuild my project a little. I installed everything that is needed and when I do: `var ColorPicker = require('react-colorpicker');` I've got same message as @importre. I've tried to do `var ColorPicker = require('react-colorpicker/pkg/index');` but then whole picker brokes. Here's what I get after:
```html
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$props:0:$color:0">#ddd</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$color:0:$_:0:$rgb:0:0">221</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$color:0:$_:0:$rgb:0:1">221</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$color:0:$_:0:$rgb:0:2">221</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$color:0:$_:0:$hsv:0:0">0</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$color:0:$_:0:$hsv:0:1">0</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$color:0:$_:0:$hsv:0:2">86.66666666666667</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$origin:0:$_:0:$rgb:0:0">221</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$origin:0:$_:0:$rgb:0:1">221</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$origin:0:$_:0:$rgb:0:2">221</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$hsv:0:$h:0">0</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$hsv:0:$s:0">0</span>
<span data-reactid=".0.0.0.1.1.$2.1:$3.2.0.$0.1.0.1:$state:0:$hsv:0:$v:0">86.66666666666667</span>
```
Earlier when it was working I have normal `div.colorpicker` with sliders, color preview etc

**Comment by patryk-g** [comment]
I installed version 0.3.9 and it works. Any newer version don't (at least for me).

So, I think I'm pleased with this solution. Thanks for your work it really helped me.

**Comment by importre** [comment]
still same error. I've checked that version is 0.3.12.
I hope to have good news soon :+1: 
thank you.

**Comment by ekonstantinidis** [comment]
+1 I have exactly the same issue. I'm using react `0.13.2` and getting the following error:

    Error: Cannot find module 'react-colorpicker' from '/Users/Manos/Projects/ui-color/src/js/components'

**Comment by ekonstantinidis** [comment]
Alright, the only way I could make it work was by removing the `browser` attribute from the `package.json`.

    "browser": "react-colorpicker.js",

So if I remove it everything is working properly!

**Comment by stayradiated** [comment]
I've removed the `browser` field from the package config.

**Comment by ekonstantinidis** [comment]
It works now! Thank you!
