### ISSUE TITLE
Mousedown and mouseup on controlled color-pickers

### ISSUE THREAD

**Issue by prewk** [stayradiated/react-colorpicker#18]
Hi, it's me again! ;)

I've got another little problem: [http://oskarthornblad.se/colorpicker-problem/](http://oskarthornblad.se/colorpicker-problem/)

Try mousedowning (holding the mouse button, duh) somewhere in the saturation picker. The marker doesn't go in the right place. Now let go of the mouse button - Bingo, it jumps to the right place.

The JS: [http://oskarthornblad.se/colorpicker-problem/index.js](http://oskarthornblad.se/colorpicker-problem/index.js)

(It works when dragging)

**Comment by stayradiated** [comment]
I think you may have the wrong github repo: https://github.com/zippyui/react-color-picker.

**Comment by prewk** [comment]
Oh, that's embarrassing. Sorry.
